### ISSUE TITLE
[BUG]: Inactive Tutorials button

### ISSUE THREAD

**Issue by dregourd** [dell/csm#1121]
### How can the Team help you today?

I try to launch the interactive tutorails but the button is inactive.
https://dell.github.io/csm-docs/docs/interactive-tutorials/

I see it works when I dezoom (I am on a laptop).

Can you help me please?

Thank you by advance,
David Regourd

**Comment by gallacher** [comment]
Hi @dregourd.  Thank you for brining this to our attention.  This has been converted to a bug so our maintainers can address the issue.

**Comment by shanmydell** [comment]
Fixed via https://github.com/dell/csm-docs/pull/998

**Comment by dregourd** [comment]
Hello, the issue is still here. 
There is a transparent frame which covers the button (on laptop screens)
Cheers,
David

**Comment by dregourd** [comment]
Thanks!
